addSbtPlugin("com.jsuereth"       % "sbt-pgp"               % "1.0.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "1.0.4")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"         % "1.5.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"       % "0.1.14")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"           % "0.6.16")
addSbtPlugin("io.get-coursier"    % "sbt-coursier"          % "1.0.0-RC3")
